id: P005418
initial_creation_type: ocr
source_metadata:
  id: bdr:W20438
  title: གསོ་བ་རིག་པའི་བསྡུས་མིང་བརྡ་བཀྲོལ་ཉིན་བྱེད་དབང་པོ
  author: ''
  volumes:
    52ecce8d8dad4b289a27e66dca1cc46f:
      image_group_id: I4843
      title: ''
      volume_number: 1
      total_pages: 522
