id: I5215C519
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T08:12:05+00:00'
last_modified: '2022-06-08T02:56:44.180495+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20438
  title: གསོ་བ་རིག་པའི་བསྡུས་མིང་བརྡ་བཀྲོལ་ཉིན་བྱེད་དབང་པོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    5E88:
      image_group_id: I4843
      title: ''
      total_pages: 522
      order: 1
      base_file: 5E88.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
